# Generated by Django 4.1.7 on 2023-02-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_added_by_role_uid_task_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='task',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='Nothing', max_length=60),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='Valid', max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
