# Generated by Django 4.1.7 on 2023-02-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_userid_alter_role_name_alter_role_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userid',
            new_name='name',
        ),
    ]
